resources:
- name: pcf-hol
  type: git
  source:
    uri: https://tichimura@github.com/tichimura/gemfire-modules-jboss.git

- name: resource-web-app
  type: git
  source:
    uri: https://tichimura@github.com/cloudfoundry-community/simple-go-web-app.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: {{cf_api}}
    username: {{cf_user}}
    password: {{cf_user_pass}}
    organization: {{cf_org}}
    space: {{cf_space}}
    skip_cert_check: false
jobs:
- name: hello-world
  plan:
  - get: pcf-hol
    trigger: true
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]
- name: job-deploy-app
  public: true
  serial: true
  plan:
    - aggregate:
      - get: pcf-hol
        trigger: true
        passed: [hello-world]
      - get: resource-web-app
    - put: resource-deploy-web-app
      params:
        manifest: resource-web-app/manifest.yml
        path: resource-web-app
